// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:388765456716:web:20d84f371f45e4979497e9',
    messagingSenderId: '388765456716',
    projectId: 'doc-app-faeed',
    authDomain: 'doc-app-faeed.firebaseapp.com',
    storageBucket: 'doc-app-faeed.firebasestorage.app',
    measurementId: 'G-SEJ9YJSL7X',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:388765456716:android:6701309b2400cdf19497e9',
    messagingSenderId: '388765456716',
    projectId: 'doc-app-faeed',
    storageBucket: 'doc-app-faeed.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:388765456716:ios:c748d594550e1c169497e9',
    messagingSenderId: '388765456716',
    projectId: 'doc-app-faeed',
    storageBucket: 'doc-app-faeed.firebasestorage.app',
    iosBundleId: 'com.example.docApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:388765456716:ios:c748d594550e1c169497e9',
    messagingSenderId: '388765456716',
    projectId: 'doc-app-faeed',
    storageBucket: 'doc-app-faeed.firebasestorage.app',
    iosBundleId: 'com.example.docApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:388765456716:web:dd2ec4ac695b0a669497e9',
    messagingSenderId: '388765456716',
    projectId: 'doc-app-faeed',
    authDomain: 'doc-app-faeed.firebaseapp.com',
    storageBucket: 'doc-app-faeed.firebasestorage.app',
    measurementId: 'G-0VPVX874JX',
  );
}
